baseURL = "https://lacafetalab.github.io/front/"
title = "Blog Front"
languageCode = "es"
DefaultContentLanguage = "es"
preserveTaxonomyNames = true
theme = "hugo.386"

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Blog Front"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Bienvenido al blog de front random!"

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Somos un equipo con muchas ganas de seguir aprendiendo y de difundir lo que aprendemos."

    # The name to display in the copyright section in the footer
    copyrightname = "CafetaLab"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Urls for social networks
    facebook = ""
    twitter = ""
    linkedin = ""
    github = "https://github.com/lacafetalab"
    gitlab = ""

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = true

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 0.2

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = true

[params.copyright]
    name = "CafetaLab"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  [[menu.main]]
    identifier = "links"
    name = "Enlaces"
    url = "/links/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

